#########################################################################
#									#
# Author: Copyright (C) 2026  Mark Grant				#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0-only					#
#									#
# Purpose:								#
# AutoMake script file to generate mge-bash-std-libs project.	`	#
#									#
#########################################################################


ACLOCAL_AMFLAGS = -I m4


AM_DISTCHECK_CONFIGURE_FLAGS = --enable-testinghacks=yes


SUBDIRS = src/prg/bash
SUBDIRS += src/prg/tests/exit-tests/test00
SUBDIRS += src/prg/tests/exit-tests/test79
SUBDIRS += src/prg/tests/output-tests/test-00-00
SUBDIRS += src/prg/tests/output-tests/test-00-01
SUBDIRS += src/prg/tests/output-tests/test-00-02
SUBDIRS += src/prg/tests/output-tests/test-00-03
SUBDIRS += src/prg/tests/output-tests/test-00-04
SUBDIRS += src/prg/tests/output-tests/test-00-05
SUBDIRS += src/prg/tests/output-tests/test-00-06
SUBDIRS += src/prg/tests/output-tests/test-00-07
SUBDIRS += src/prg/tests/output-tests/test-00-08
SUBDIRS += src/prg/tests/output-tests/test-00-09
SUBDIRS += src/prg/tests/output-tests/test-00-10
SUBDIRS += src/prg/tests/output-tests/test-00-11
SUBDIRS += src/prg/tests/output-tests/test-00-12
SUBDIRS += src/prg/tests/output-tests/test-00-13
SUBDIRS += src/prg/tests/output-tests/test-00-14
SUBDIRS += src/prg/tests/output-tests/test-00-15
SUBDIRS += src/prg/tests/output-tests/test-01-00
SUBDIRS += src/prg/tests/output-tests/test-01-01
SUBDIRS += src/prg/tests/output-tests/test-01-02
SUBDIRS += src/prg/tests/output-tests/test-01-03
SUBDIRS += src/prg/tests/output-tests/test-01-04
SUBDIRS += src/prg/tests/output-tests/test-01-05
SUBDIRS += src/prg/tests/output-tests/test-01-06
SUBDIRS += src/prg/tests/output-tests/test-01-07
SUBDIRS += src/prg/tests/output-tests/test-01-08
SUBDIRS += src/prg/tests/output-tests/test-01-09
SUBDIRS += src/prg/tests/output-tests/test-01-10
SUBDIRS += src/prg/tests/output-tests/test-01-11
SUBDIRS += src/prg/tests/output-tests/test-01-12
SUBDIRS += src/prg/tests/output-tests/test-01-13
SUBDIRS += src/prg/tests/output-tests/test-01-14
SUBDIRS += src/prg/tests/output-tests/test-01-15
SUBDIRS += src/prg/tests/output-tests/test-02-00
SUBDIRS += src/prg/tests/output-tests/test-02-01
SUBDIRS += src/prg/tests/output-tests/test-02-02
SUBDIRS += src/prg/tests/output-tests/test-02-03
SUBDIRS += src/prg/tests/output-tests/test-02-04
SUBDIRS += src/prg/tests/output-tests/test-02-05
SUBDIRS += src/prg/tests/output-tests/test-02-06
SUBDIRS += src/prg/tests/output-tests/test-02-07
SUBDIRS += src/prg/tests/output-tests/test-02-08
SUBDIRS += src/prg/tests/output-tests/test-02-09
SUBDIRS += src/prg/tests/output-tests/test-02-10
SUBDIRS += src/prg/tests/output-tests/test-02-11
SUBDIRS += src/prg/tests/output-tests/test-02-12
SUBDIRS += src/prg/tests/output-tests/test-02-13
SUBDIRS += src/prg/tests/output-tests/test-02-14
SUBDIRS += src/prg/tests/output-tests/test-02-15
SUBDIRS += src/prg/tests/output-tests/test-03-00
SUBDIRS += src/prg/tests/output-tests/test-03-01
SUBDIRS += src/prg/tests/output-tests/test-03-02
SUBDIRS += src/prg/tests/output-tests/test-03-03
SUBDIRS += src/prg/tests/output-tests/test-03-04
SUBDIRS += src/prg/tests/output-tests/test-03-05
SUBDIRS += src/prg/tests/output-tests/test-03-06
SUBDIRS += src/prg/tests/output-tests/test-03-07
SUBDIRS += src/prg/tests/output-tests/test-03-08
SUBDIRS += src/prg/tests/output-tests/test-03-09
SUBDIRS += src/prg/tests/output-tests/test-03-10
SUBDIRS += src/prg/tests/output-tests/test-03-11
SUBDIRS += src/prg/tests/output-tests/test-03-12
SUBDIRS += src/prg/tests/output-tests/test-03-13
SUBDIRS += src/prg/tests/output-tests/test-03-14
SUBDIRS += src/prg/tests/output-tests/test-03-15
SUBDIRS += src/prg/tests/output-tests/test-05-00
SUBDIRS += src/prg/tests/output-tests/test-05-01
SUBDIRS += src/prg/tests/output-tests/test-05-02
SUBDIRS += src/prg/tests/output-tests/test-05-03
SUBDIRS += src/prg/tests/output-tests/test-05-04
SUBDIRS += src/prg/tests/output-tests/test-05-05
SUBDIRS += src/prg/tests/output-tests/test-05-06
SUBDIRS += src/prg/tests/output-tests/test-05-07
SUBDIRS += src/prg/tests/output-tests/test-05-08
SUBDIRS += src/prg/tests/output-tests/test-05-09
SUBDIRS += src/prg/tests/output-tests/test-05-10
SUBDIRS += src/prg/tests/output-tests/test-05-11
SUBDIRS += src/prg/tests/output-tests/test-05-12
SUBDIRS += src/prg/tests/output-tests/test-05-13
SUBDIRS += src/prg/tests/output-tests/test-05-14
SUBDIRS += src/prg/tests/output-tests/test-05-15
SUBDIRS += src/prg/tests/output-tests/test-06-00
SUBDIRS += src/prg/tests/output-tests/test-06-01
SUBDIRS += src/prg/tests/output-tests/test-06-02
SUBDIRS += src/prg/tests/output-tests/test-06-03
SUBDIRS += src/prg/tests/output-tests/test-06-04
SUBDIRS += src/prg/tests/output-tests/test-06-05
SUBDIRS += src/prg/tests/output-tests/test-06-06
SUBDIRS += src/prg/tests/output-tests/test-06-07
SUBDIRS += src/prg/tests/output-tests/test-06-08
SUBDIRS += src/prg/tests/output-tests/test-06-09
SUBDIRS += src/prg/tests/output-tests/test-06-10
SUBDIRS += src/prg/tests/output-tests/test-06-11
SUBDIRS += src/prg/tests/output-tests/test-06-12
SUBDIRS += src/prg/tests/output-tests/test-06-13
SUBDIRS += src/prg/tests/output-tests/test-06-14
SUBDIRS += src/prg/tests/output-tests/test-06-15
SUBDIRS += src/prg/tests/shellcheck
SUBDIRS += src/prg/tests/trap-tests/test00
SUBDIRS += src/prg/tests/version-tests/test00
SUBDIRS += src/prg/run-tests


doc_DATA = AUTHORS ChangeLog COPYING NEWS README


EXTRA_DIST = $(srcdir)/AUTHORS $(srcdir)/ChangeLog $(srcdir)/COPYING \
		$(srcdir)/NEWS $(srcdir)/README $(srcdir)/misc


srctarball:
	@cwd="$${PWD}" && \
	targ="$${cwd}/@PACKAGE_TARNAME@-@PACKAGE_VERSION@.tar.gz" && \
	cd @srcdir@ && \
	echo "making srctarball from @srcdir@" && \
	echo "GA	$${targ}" && \
	git archive --format=tar.gz \
		--prefix=@PACKAGE_TARNAME@-@PACKAGE_VERSION@/ \
		--output=$${targ} \
		HEAD && \
	cd -


sign_tarball:
	rm -f @PACKAGE_TARNAME@-@PACKAGE_VERSION@.tar.gz.asc
	gpg --armor --detach-sign @PACKAGE_TARNAME@-@PACKAGE_VERSION@.tar.gz

